name: leeds_python_workshop

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - pillow
  - tifffile
  - jupyter
  - pip
  - pip:
      - AFMReader